mkdir my_out
sol\frequencia.py < in\frequencia_1 > my_out\frequencia_1
sol\frequencia.py < in\frequencia_2 > my_out\frequencia_2
sol\frequencia.py < in\frequencia_3 > my_out\frequencia_3
sol\frequencia.py < in\frequencia_4 > my_out\frequencia_4
sol\frequencia.py < in\frequencia_5 > my_out\frequencia_5
sol\frequencia.py < in\frequencia_6 > my_out\frequencia_6
sol\frequencia.py < in\frequencia_7 > my_out\frequencia_7
sol\frequencia.py < in\frequencia_8 > my_out\frequencia_8
sol\frequencia.py < in\frequencia_9 > my_out\frequencia_9
sol\frequencia.py < in\frequencia_10 > my_out\frequencia_10
sol\frequencia.py < in\frequencia_11 > my_out\frequencia_11
sol\frequencia.py < in\frequencia_12 > my_out\frequencia_12
sol\frequencia.py < in\frequencia_13 > my_out\frequencia_13
sol\frequencia.py < in\frequencia_14 > my_out\frequencia_14
sol\frequencia.py < in\frequencia_15 > my_out\frequencia_15
sol\frequencia.py < in\frequencia_16 > my_out\frequencia_16
sol\frequencia.py < in\frequencia_17 > my_out\frequencia_17
sol\frequencia.py < in\frequencia_18 > my_out\frequencia_18
sol\frequencia.py < in\frequencia_19 > my_out\frequencia_19
sol\frequencia.py < in\frequencia_20 > my_out\frequencia_20
sol\frequencia.py < in\frequencia_21 > my_out\frequencia_21
sol\frequencia.py < in\frequencia_22 > my_out\frequencia_22
sol\frequencia.py < in\frequencia_23 > my_out\frequencia_23
sol\frequencia.py < in\frequencia_24 > my_out\frequencia_24
sol\frequencia.py < in\frequencia_25 > my_out\frequencia_25
sol\frequencia.py < in\frequencia_26 > my_out\frequencia_26
sol\frequencia.py < in\frequencia_27 > my_out\frequencia_27
sol\frequencia.py < in\frequencia_28 > my_out\frequencia_28
sol\frequencia.py < in\frequencia_29 > my_out\frequencia_29
sol\frequencia.py < in\frequencia_30 > my_out\frequencia_30
sol\frequencia.py < in\frequencia_31 > my_out\frequencia_31
sol\frequencia.py < in\frequencia_32 > my_out\frequencia_32
sol\frequencia.py < in\frequencia_33 > my_out\frequencia_33
sol\frequencia.py < in\frequencia_34 > my_out\frequencia_34
sol\frequencia.py < in\frequencia_35 > my_out\frequencia_35
sol\frequencia.py < in\frequencia_36 > my_out\frequencia_36
sol\frequencia.py < in\frequencia_37 > my_out\frequencia_37
sol\frequencia.py < in\frequencia_38 > my_out\frequencia_38
sol\frequencia.py < in\frequencia_39 > my_out\frequencia_39
sol\frequencia.py < in\frequencia_40 > my_out\frequencia_40
sol\frequencia.py < in\frequencia_41 > my_out\frequencia_41
sol\frequencia.py < in\frequencia_42 > my_out\frequencia_42
sol\frequencia.py < in\frequencia_43 > my_out\frequencia_43
sol\frequencia.py < in\frequencia_44 > my_out\frequencia_44
sol\frequencia.py < in\frequencia_45 > my_out\frequencia_45
sol\frequencia.py < in\frequencia_46 > my_out\frequencia_46
sol\frequencia.py < in\frequencia_47 > my_out\frequencia_47
sol\frequencia.py < in\frequencia_48 > my_out\frequencia_48
sol\frequencia.py < in\frequencia_49 > my_out\frequencia_49
sol\frequencia.py < in\frequencia_50 > my_out\frequencia_50
sol\frequencia.py < in\frequencia_51 > my_out\frequencia_51
sol\frequencia.py < in\frequencia_52 > my_out\frequencia_52
sol\frequencia.py < in\frequencia_53 > my_out\frequencia_53
sol\frequencia.py < in\frequencia_54 > my_out\frequencia_54
sol\frequencia.py < in\frequencia_55 > my_out\frequencia_55
sol\frequencia.py < in\frequencia_56 > my_out\frequencia_56
sol\frequencia.py < in\frequencia_57 > my_out\frequencia_57
sol\frequencia.py < in\frequencia_58 > my_out\frequencia_58
sol\frequencia.py < in\frequencia_59 > my_out\frequencia_59
sol\frequencia.py < in\frequencia_60 > my_out\frequencia_60
sol\frequencia.py < in\frequencia_61 > my_out\frequencia_61
sol\frequencia.py < in\frequencia_62 > my_out\frequencia_62
sol\frequencia.py < in\frequencia_63 > my_out\frequencia_63
sol\frequencia.py < in\frequencia_64 > my_out\frequencia_64
sol\frequencia.py < in\frequencia_65 > my_out\frequencia_65
sol\frequencia.py < in\frequencia_66 > my_out\frequencia_66
sol\frequencia.py < in\frequencia_67 > my_out\frequencia_67
sol\frequencia.py < in\frequencia_68 > my_out\frequencia_68
sol\frequencia.py < in\frequencia_69 > my_out\frequencia_69
sol\frequencia.py < in\frequencia_70 > my_out\frequencia_70
sol\frequencia.py < in\frequencia_71 > my_out\frequencia_71
sol\frequencia.py < in\frequencia_72 > my_out\frequencia_72
sol\frequencia.py < in\frequencia_73 > my_out\frequencia_73
sol\frequencia.py < in\frequencia_74 > my_out\frequencia_74
sol\frequencia.py < in\frequencia_75 > my_out\frequencia_75
sol\frequencia.py < in\frequencia_76 > my_out\frequencia_76
sol\frequencia.py < in\frequencia_77 > my_out\frequencia_77
sol\frequencia.py < in\frequencia_78 > my_out\frequencia_78
sol\frequencia.py < in\frequencia_79 > my_out\frequencia_79
sol\frequencia.py < in\frequencia_80 > my_out\frequencia_80
sol\frequencia.py < in\frequencia_81 > my_out\frequencia_81
sol\frequencia.py < in\frequencia_82 > my_out\frequencia_82
sol\frequencia.py < in\frequencia_83 > my_out\frequencia_83
sol\frequencia.py < in\frequencia_84 > my_out\frequencia_84
sol\frequencia.py < in\frequencia_85 > my_out\frequencia_85
sol\frequencia.py < in\frequencia_86 > my_out\frequencia_86
sol\frequencia.py < in\frequencia_87 > my_out\frequencia_87
sol\frequencia.py < in\frequencia_88 > my_out\frequencia_88
sol\frequencia.py < in\frequencia_89 > my_out\frequencia_89
sol\frequencia.py < in\frequencia_90 > my_out\frequencia_90
sol\frequencia.py < in\frequencia_91 > my_out\frequencia_91
sol\frequencia.py < in\frequencia_92 > my_out\frequencia_92
sol\frequencia.py < in\frequencia_93 > my_out\frequencia_93
sol\frequencia.py < in\frequencia_94 > my_out\frequencia_94
sol\frequencia.py < in\frequencia_95 > my_out\frequencia_95
sol\frequencia.py < in\frequencia_96 > my_out\frequencia_96
sol\frequencia.py < in\frequencia_97 > my_out\frequencia_97
sol\frequencia.py < in\frequencia_98 > my_out\frequencia_98
sol\frequencia.py < in\frequencia_99 > my_out\frequencia_99
pause
fc /L my_out\* out\*
pause
