mkdir my_out
sol\bingo.py < in\bingo_1 > my_out\bingo_1
sol\bingo.py < in\bingo_2 > my_out\bingo_2
sol\bingo.py < in\bingo_3 > my_out\bingo_3
sol\bingo.py < in\bingo_4 > my_out\bingo_4
sol\bingo.py < in\bingo_5 > my_out\bingo_5
sol\bingo.py < in\bingo_6 > my_out\bingo_6
sol\bingo.py < in\bingo_7 > my_out\bingo_7
sol\bingo.py < in\bingo_8 > my_out\bingo_8
sol\bingo.py < in\bingo_9 > my_out\bingo_9
sol\bingo.py < in\bingo_10 > my_out\bingo_10
sol\bingo.py < in\bingo_11 > my_out\bingo_11
sol\bingo.py < in\bingo_12 > my_out\bingo_12
sol\bingo.py < in\bingo_13 > my_out\bingo_13
sol\bingo.py < in\bingo_14 > my_out\bingo_14
sol\bingo.py < in\bingo_15 > my_out\bingo_15
sol\bingo.py < in\bingo_16 > my_out\bingo_16
sol\bingo.py < in\bingo_17 > my_out\bingo_17
sol\bingo.py < in\bingo_18 > my_out\bingo_18
sol\bingo.py < in\bingo_19 > my_out\bingo_19
sol\bingo.py < in\bingo_20 > my_out\bingo_20
sol\bingo.py < in\bingo_21 > my_out\bingo_21
sol\bingo.py < in\bingo_22 > my_out\bingo_22
sol\bingo.py < in\bingo_23 > my_out\bingo_23
sol\bingo.py < in\bingo_24 > my_out\bingo_24
sol\bingo.py < in\bingo_25 > my_out\bingo_25
sol\bingo.py < in\bingo_26 > my_out\bingo_26
sol\bingo.py < in\bingo_27 > my_out\bingo_27
sol\bingo.py < in\bingo_28 > my_out\bingo_28
sol\bingo.py < in\bingo_29 > my_out\bingo_29
sol\bingo.py < in\bingo_30 > my_out\bingo_30
sol\bingo.py < in\bingo_31 > my_out\bingo_31
sol\bingo.py < in\bingo_32 > my_out\bingo_32
sol\bingo.py < in\bingo_33 > my_out\bingo_33
sol\bingo.py < in\bingo_34 > my_out\bingo_34
sol\bingo.py < in\bingo_35 > my_out\bingo_35
sol\bingo.py < in\bingo_36 > my_out\bingo_36
sol\bingo.py < in\bingo_37 > my_out\bingo_37
sol\bingo.py < in\bingo_38 > my_out\bingo_38
sol\bingo.py < in\bingo_39 > my_out\bingo_39
sol\bingo.py < in\bingo_40 > my_out\bingo_40
sol\bingo.py < in\bingo_41 > my_out\bingo_41
sol\bingo.py < in\bingo_42 > my_out\bingo_42
sol\bingo.py < in\bingo_43 > my_out\bingo_43
sol\bingo.py < in\bingo_44 > my_out\bingo_44
sol\bingo.py < in\bingo_45 > my_out\bingo_45
sol\bingo.py < in\bingo_46 > my_out\bingo_46
sol\bingo.py < in\bingo_47 > my_out\bingo_47
sol\bingo.py < in\bingo_48 > my_out\bingo_48
sol\bingo.py < in\bingo_49 > my_out\bingo_49
sol\bingo.py < in\bingo_50 > my_out\bingo_50
sol\bingo.py < in\bingo_51 > my_out\bingo_51
sol\bingo.py < in\bingo_52 > my_out\bingo_52
sol\bingo.py < in\bingo_53 > my_out\bingo_53
sol\bingo.py < in\bingo_54 > my_out\bingo_54
pause
fc /L my_out\* out\*
pause
