mkdir my_out
sol\mario.py < in\teste_0.in > my_out\teste_0.sol
sol\mario.py < in\teste_1.in > my_out\teste_1.sol
sol\mario.py < in\teste_2.in > my_out\teste_2.sol
sol\mario.py < in\teste_3.in > my_out\teste_3.sol
sol\mario.py < in\teste_4.in > my_out\teste_4.sol
sol\mario.py < in\teste_5.in > my_out\teste_5.sol
sol\mario.py < in\teste_6.in > my_out\teste_6.sol
sol\mario.py < in\teste_7.in > my_out\teste_7.sol
sol\mario.py < in\teste_8.in > my_out\teste_8.sol
sol\mario.py < in\teste_9.in > my_out\teste_9.sol
sol\mario.py < in\teste_10.in > my_out\teste_10.sol
sol\mario.py < in\teste_11.in > my_out\teste_11.sol
sol\mario.py < in\teste_12.in > my_out\teste_12.sol
sol\mario.py < in\teste_13.in > my_out\teste_13.sol
sol\mario.py < in\teste_14.in > my_out\teste_14.sol
sol\mario.py < in\teste_15.in > my_out\teste_15.sol
sol\mario.py < in\teste_16.in > my_out\teste_16.sol
sol\mario.py < in\teste_17.in > my_out\teste_17.sol
sol\mario.py < in\teste_18.in > my_out\teste_18.sol
sol\mario.py < in\teste_19.in > my_out\teste_19.sol
sol\mario.py < in\teste_20.in > my_out\teste_20.sol
sol\mario.py < in\teste_21.in > my_out\teste_21.sol
sol\mario.py < in\teste_22.in > my_out\teste_22.sol
sol\mario.py < in\teste_23.in > my_out\teste_23.sol
sol\mario.py < in\teste_24.in > my_out\teste_24.sol
sol\mario.py < in\teste_25.in > my_out\teste_25.sol
sol\mario.py < in\teste_26.in > my_out\teste_26.sol
sol\mario.py < in\teste_27.in > my_out\teste_27.sol
sol\mario.py < in\teste_28.in > my_out\teste_28.sol
sol\mario.py < in\teste_29.in > my_out\teste_29.sol
sol\mario.py < in\teste_30.in > my_out\teste_30.sol
sol\mario.py < in\teste_31.in > my_out\teste_31.sol
sol\mario.py < in\teste_32.in > my_out\teste_32.sol
sol\mario.py < in\teste_33.in > my_out\teste_33.sol
sol\mario.py < in\teste_34.in > my_out\teste_34.sol
sol\mario.py < in\teste_35.in > my_out\teste_35.sol
sol\mario.py < in\teste_36.in > my_out\teste_36.sol
sol\mario.py < in\teste_37.in > my_out\teste_37.sol
sol\mario.py < in\teste_38.in > my_out\teste_38.sol
sol\mario.py < in\teste_39.in > my_out\teste_39.sol
sol\mario.py < in\teste_40.in > my_out\teste_40.sol
sol\mario.py < in\teste_41.in > my_out\teste_41.sol
sol\mario.py < in\teste_42.in > my_out\teste_42.sol
sol\mario.py < in\teste_43.in > my_out\teste_43.sol
sol\mario.py < in\teste_44.in > my_out\teste_44.sol
sol\mario.py < in\teste_45.in > my_out\teste_45.sol
sol\mario.py < in\teste_46.in > my_out\teste_46.sol
sol\mario.py < in\teste_47.in > my_out\teste_47.sol
sol\mario.py < in\teste_48.in > my_out\teste_48.sol
sol\mario.py < in\teste_49.in > my_out\teste_49.sol
sol\mario.py < in\teste_50.in > my_out\teste_50.sol
sol\mario.py < in\teste_51.in > my_out\teste_51.sol
sol\mario.py < in\teste_52.in > my_out\teste_52.sol
sol\mario.py < in\teste_53.in > my_out\teste_53.sol
sol\mario.py < in\teste_54.in > my_out\teste_54.sol
sol\mario.py < in\teste_55.in > my_out\teste_55.sol
sol\mario.py < in\teste_56.in > my_out\teste_56.sol
sol\mario.py < in\teste_57.in > my_out\teste_57.sol
sol\mario.py < in\teste_58.in > my_out\teste_58.sol
sol\mario.py < in\teste_59.in > my_out\teste_59.sol
sol\mario.py < in\teste_60.in > my_out\teste_60.sol
sol\mario.py < in\teste_61.in > my_out\teste_61.sol
sol\mario.py < in\teste_62.in > my_out\teste_62.sol
sol\mario.py < in\teste_63.in > my_out\teste_63.sol
sol\mario.py < in\teste_64.in > my_out\teste_64.sol
sol\mario.py < in\teste_65.in > my_out\teste_65.sol
sol\mario.py < in\teste_66.in > my_out\teste_66.sol
sol\mario.py < in\teste_67.in > my_out\teste_67.sol
sol\mario.py < in\teste_68.in > my_out\teste_68.sol
sol\mario.py < in\teste_69.in > my_out\teste_69.sol
sol\mario.py < in\teste_70.in > my_out\teste_70.sol
sol\mario.py < in\teste_71.in > my_out\teste_71.sol
sol\mario.py < in\teste_72.in > my_out\teste_72.sol
sol\mario.py < in\teste_73.in > my_out\teste_73.sol
sol\mario.py < in\teste_74.in > my_out\teste_74.sol
sol\mario.py < in\teste_75.in > my_out\teste_75.sol
sol\mario.py < in\teste_76.in > my_out\teste_76.sol
sol\mario.py < in\teste_77.in > my_out\teste_77.sol
sol\mario.py < in\teste_78.in > my_out\teste_78.sol
sol\mario.py < in\teste_79.in > my_out\teste_79.sol
sol\mario.py < in\teste_80.in > my_out\teste_80.sol
sol\mario.py < in\teste_81.in > my_out\teste_81.sol
sol\mario.py < in\teste_82.in > my_out\teste_82.sol
sol\mario.py < in\teste_83.in > my_out\teste_83.sol
sol\mario.py < in\teste_84.in > my_out\teste_84.sol
sol\mario.py < in\teste_85.in > my_out\teste_85.sol
sol\mario.py < in\teste_86.in > my_out\teste_86.sol
sol\mario.py < in\teste_87.in > my_out\teste_87.sol
sol\mario.py < in\teste_88.in > my_out\teste_88.sol
sol\mario.py < in\teste_89.in > my_out\teste_89.sol
pause
fc /L my_out\* out\*
pause
